namespace LongDK.Audio
{
    // This file is auto-generated by the AudioLibraryEditor.
    // Do not modify manually unless you know what you are doing.
    public enum AudioID
    {
        None = 0,
        // [GENERATED_ENUMS_START]
        UI_Click,
        Music_MainMenu,
        SFX_Explosion,
                HaduinTown,
        // [GENERATED_ENUMS_END]
    }
}