namespace LongDK.UI
{
    // Auto-generated by UIRegistryEditor
    public enum UI_ID
    {
        None = 0,
        // [GENERATED_ENUMS_START]
        MainMenu,
        GameplayHUD,
        // [GENERATED_ENUMS_END]
    }

    public enum UILayer
    {
        Background = 0,
        Gameplay = 100,
        Window = 200,
        Popup = 300,
        System = 400
    }
}